name: 'Release new version'

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: 'Release simple repository'
    runs-on:  ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: release-please
        uses: google-github-actions/release-please-action@v3
        with:
          # Multiple release types are supported, check github action for others
          release-type: simple
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
